# Generated by Django 5.1.4 on 2024-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrukturSekolah',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('Nip', models.CharField(blank=True, max_length=15, unique=True)),
                ('Nuptk', models.CharField(max_length=15)),
                ('Nama', models.CharField(max_length=50)),
                ('JenisKelamin', models.CharField(blank=True, max_length=15, null=True)),
                ('TanggalLahir', models.DateField(blank=True, null=True)),
                ('TempatLahir', models.CharField(blank=True, max_length=40, null=True)),
                ('Agama', models.CharField(blank=True, max_length=20, null=True)),
                ('Alamat', models.TextField(blank=True, null=True)),
                ('NoTelepon', models.CharField(blank=True, max_length=18, null=True)),
                ('Posisi', models.CharField(max_length=20)),
                ('Kelas', models.CharField(max_length=20)),
                ('Materi', models.JSONField()),
                ('Tanggal_Masuk', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
